set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
# Don't rename windows automatically
set-option -g allow-rename off
set-option -g status-position top

# reload config file (change file location to your tmux.conf)
bind r source-file  ~/.tmux.conf \; display "Reloaded!"

